<center>
<a href="" ><img src="./iris.jpeg" style="float:left; max-width: 200px; height: 145px; "/></a> 
<a href="https://github.com/hafs96/Iris-Dataset-Classification-with-Neural-Networks.git" ><img src="./git.jpeg" style="float:right; max-width: 50px; display: inline " /></a>
</center>
<div id="report" style="text-align: center; padding: 10px; background-color:rgb(17, 16, 16); border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); ">
  <h1 style="font-size: 2.2em; font-family: 'Georgia', serif; color:rgb(247, 239, 248); margin-bottom: 10px;">
    Iris Neural Network Experiment
  </h1>
  <p style="font-size: 1.1em; font-family: 'Arial', sans-serif; color:rgb(227, 231, 235); margin: 5px 0;">
    Prepared by :  ZIAN Hafsa
  </p>
  <div style="margin-top: 15px; padding: 5px; background-color: #ecf0f1; border-left: 4px solid rgb(127, 50, 129); border-radius: 8px; display: inline-block; max-width: 60%;">
    <p style="font-size: 1.1em; font-family: 'Arial', sans-serif; color:rgb(16, 17, 17); margin: 0; font-style: italic;">
      Supervised by : 
      <span style="font-weight: bold; color:rgb(129, 27, 116);">Prof. EL YAZIDI Youness</span>
    </p>
  </div>
</div> 

<div id="report" style="text-align: center; padding: 20px; ">
  <h1 style="font-size: 2em; font-family: 'Georgia', serif; color: #fff; background-color: #333; padding: 10px;">  
  &#9733; Report Content   &#9733; </h1>
</div>

1. <a href="#intro">Introduction</a><br>

2. <a href="#dataset">Iris Dataset</a><br>

3. <a href="#methodology">Methodology</a><br>
   3.1 <a href="#data_preparation">Data Preparation</a><br>
   3.2 <a href="#splitting">Splitting Training, Validation, and Testing Sets</a><br>

4. <a href="#activation_functions">Activation Function Comparison</a><br>
   4.1 <a href="#hidden_layer">Hidden Layer Activation Functions</a><br>
   4.2 <a href="#output_layer">Output Layer Activation Functions</a><br>

5. <a href="#loss_functions">Loss Function Evaluation</a><br>
   5.1 <a href="#cross_entropy">Cross-Entropy Loss</a><br>
   5.2 <a href="#hinge_loss">Hinge Loss</a><br>

6. <a href="#optimizers">Optimizer Selection</a><br>
   6.1 <a href="#rmsprop">RMSProp Optimizer</a><br>
   6.2 <a href="#adam">Adam Optimizer</a><br>

7. <a href="#evaluation_metrics">Evaluation Metrics</a><br>

8. <a href="#cross_validation">Cross-Validation Analysis</a><br>

9. <a href="#results">Results and Discussion</a><br>

10. <a href="#conclusion">Conclusion and Future Work</a><br>


# 1.Introduction<span id="intro"></span>


## Problem Statement
Classification is a fundamental task in machine learning, and the Iris dataset is a well-known benchmark for testing classification models. It consists of three flower species: Iris Setosa, Iris Versicolor, and Iris Virginica, each represented by four numerical features: sepal length, sepal width, petal length, and petal width.

In this study, we aim to develop a neural network with a single hidden layer to classify these species accurately. We will experiment with different activation functions, loss functions, and optimizers to determine the most effective configuration.

## Study Objectives
The primary goals of this project are to:

- Build a feedforward neural network for classifying Iris flowers.
- Compare various activation functions (Sigmoid, Tanh, ReLU) in the hidden layer.
- Evaluate the performance of Softmax vs. Sigmoid in the output layer.
- Test different loss functions (Cross-Entropy and Hinge Loss) and analyze their impact.
- Compare the effectiveness of RMSProp and Adam optimizers.
- Assess the model using appropriate evaluation metrics and cross-validation techniques.
- Improve model generalization by incorporating a validation set in addition to training and testing.


# 2. Iris Dataset <span id="dataset"></span>

In [1]:
## imports and preliminaries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [13]:
## Loading the Iris Dataset
data = load_iris()

# 3. Methodology<span id="methodology"></span>

### 3.1. Data Preparation <span id="data_preparation"></span> 

In [14]:
X, y = data.data, data.target
encoder = OneHotEncoder(sparse_output=False)
Y = encoder.fit_transform(y.reshape(-1, 1))

### 3.2. Splitting Training, Validation, and Testing Sets <span id="splitting"></span>  

In [17]:
## Split the dataset into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [18]:
print('Iris data: ')
print(data.data[:10])

Iris data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


# 4. Activation Function Comparison <span id="activation_functions"></span>

### 4.1. Hidden Layer Activation Functions <span id="hidden_layer"></span>

In [19]:
hidden_activations = ['sigmoid', 'tanh', 'relu']

### 4.2. Output Layer Activation Functions<span id="output_layer"></span>

In [20]:
output_activations = ['sigmoid', 'softmax']

In [ ]:
from tensorflow.keras.metrics import Accuracy
# Prepare for plotting the loss decay
plt.figure(figsize=(12, 8))

for hidden_activation in hidden_activations:
    for output_activation in output_activations:
        # Build the model
        model = Sequential()
        model.add(Dense(10, input_dim=X.shape[1], activation=hidden_activation))  # Hidden layer
        model.add(Dense(3, activation=output_activation))  # Output layer (3 classes)

        # Compile the model
        model.compile(optimizer=SGD(), loss='mean_squared_error', metrics=[Accuracy()])

        # Train the model
        history = model.fit(X_train, Y_train, epochs=100, batch_size=10, verbose=0, validation_data=(X_test, Y_test))

        # Plot the loss
        plt.plot(history.history['loss'], label=f'{hidden_activation}-{output_activation}')

        # Evaluate the model
        _, accuracy = model.evaluate(X_test, Y_test, verbose=0)
        print(f"Accuracy for hidden activation {hidden_activation} and output activation {output_activation}: {accuracy * 100:.2f}%")

# Customize the plot
plt.title("Loss decay for different activation functions")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend(loc='best')
plt.show()

Accuracy for hidden activation sigmoid and output activation sigmoid: 0.00%
Accuracy for hidden activation sigmoid and output activation softmax: 0.00%
Accuracy for hidden activation tanh and output activation sigmoid: 0.00%
Accuracy for hidden activation tanh and output activation softmax: 0.00%


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, RMSprop, Adam

# Charger et préparer les données
data = load_iris()
X, y = data.data, data.target
encoder = OneHotEncoder(sparse=False)
Y = encoder.fit_transform(y.reshape(-1, 1))

# Diviser les données en ensemble d'entraînement, validation et test
X_train, X_val_test, Y_train, Y_val_test = train_test_split(X, Y, test_size=0.3, random_state=42)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_test, Y_val_test, test_size=0.5, random_state=42)

# Définition des combinaisons de fonctions d'activation et de coût
hidden_activation = 'relu'
output_activation = 'softmax'
loss_functions = ['categorical_crossentropy', 'hinge']
optimizers = {'RMSprop': RMSprop(learning_rate=0.01), 'Adam': Adam(learning_rate=0.01)}

# Stocker les pertes et précisions
losses = {}
accuracies = {}

# Fonction pour créer et entraîner le modèle
def train_model(loss_function, optimizer_name):
    model = Sequential([
        Dense(10, activation=hidden_activation, input_shape=(4,)),
        Dense(3, activation=output_activation)
    ])
    
    model.compile(optimizer=optimizers[optimizer_name], loss=loss_function, metrics=['accuracy'])
    
    history = model.fit(X_train, Y_train, epochs=100, verbose=0, validation_data=(X_val, Y_val))
    
    test_loss, test_acc = model.evaluate(X_test, Y_test, verbose=0)
    losses[f"{loss_function}_{optimizer_name}"] = history.history['loss']
    accuracies[f"{loss_function}_{optimizer_name}"] = test_acc
    
    return model

# Entraînement des modèles pour différentes fonctions de coût et optimisateurs
for loss_function in loss_functions:
    for optimizer_name in optimizers.keys():
        train_model(loss_function, optimizer_name)

# Tracer les courbes de perte
plt.figure(figsize=(10, 6))
for key, loss in losses.items():
    plt.plot(loss, label=key)
plt.xlabel("Époque")
plt.ylabel("Perte")
plt.title("Évolution de la perte pour différentes fonctions de coût et optimisateurs")
plt.legend()
plt.show()

# Affichage des précisions
for key, acc in accuracies.items():
    print(f"Modèle {key} - Accuracy: {acc:.4f}")

# Validation croisée
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', solver='adam', max_iter=1000, random_state=42)
scores = cross_val_score(mlp, X, y, cv=5)
print("Scores de validation croisée:", scores)
print("Moyenne des scores:", scores.mean())
